version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          # Wildcards match unlimited arbitrary characters (or none)
          dependency_name: "boto3"
