version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "monthly"
    target_branch: "master"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          # Wildcards match unlimited arbitrary characters (or none)
          dependency_name: "boto3"
          dependency_name: "pytest"
          dependency_name: "pytest-mock"
          dependency_name: "slackclient"
