version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_labels:
    automerged_updates:
      - match:
          # Wildcards match unlimited arbitrary characters (or none)
          dependency_name: "boto3"
